F multicolumn combobox (~2940)
simplic/simplic-filestructure pull request #85
Opened 2022-04-26 14:46 UTC by MaxPatyk

2022-04-26 15:30 UTC, simplicbe commented on release-notes.xml
> +	<Change type="feature">Adds a new window to forwarded a document with the multicolumn-combobox.</Change>
```suggestion
    <Change type="feature">Adds a new window to forwarded a document with the multicolumn-combobox.</Change>
```

2022-04-27 06:34 UTC, MEichhoff requested changes

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/MultiItemBoxViewModel.cs
> +        public string CommentText { get; set; }
comments

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/MultiItemBox.xaml.cs
> +        public MultiItemBox(Dictionary<string, string> dictParams)
comment

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/MultiItemBoxViewModel.cs
> +        public string CommentText { get; set; }
spacing

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/WorkflowApplicationHelper.cs
> +            dictParams.Add("[WorkflowId]", "0a2e6fa8-2ee9-4d2e-a6e1-48cb2bf66078");
dont use magical strings

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/WorkflowApplicationHelper.cs
> +            var test2 = win.DataContext;
test should not the name of a variable

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/WorkflowApplicationHelper.cs
> +                    StackGuid = Guid.Parse("12c9b95b-bd33-4fa0-9ca1-05e11122018c") // TODO: Remove magic string
remember the todo

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/WorkflowApplicationHelper.cs
> +            var test2 = win.DataContext;
test is not a valid variable name

2022-04-27 06:34 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/WorkflowApplicationHelper.cs
> +                    };
a lot of this seems to be implemented twice, is it worth to move it to a seperate method?

2022-04-27 09:29 UTC, MaxPatyk commented
![image](https://user-images.githubusercontent.com/89005330/165487799-16192622-2b80-464d-a685-63326e26400d.png)

2022-04-27 14:07 UTC, MEichhoff requested changes

2022-04-27 14:07 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/MultiItemBoxViewModel.cs
> +    public class MultiItemBoxViewModel : ViewModelBase
same with renaming

2022-04-27 14:07 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/WorkflowApplicationHelper.cs
> +                    MessageBox.Show("Workflow für Zielbenutzer nicht gefunden.", "Workflow nicht gefunden", MessageBoxButton.OK, MessageBoxImage.Information);
remember the todo

2022-04-27 14:07 UTC, MEichhoff commented on src/Simplic.FileStructure.Workflow.UI/WorkflowApplicationHelper.cs
> +                    var workflowId = (Guid)fileStructureDocumentPathService.Get(documentPathId).WorkflowId;
possible nre?

2022-04-28 08:09 UTC, MEichhoff approved these changes

2022-04-28 08:12 UTC, merged